name: "Hello World Workflow"

on:
  push:
    branches: ["develop"]

jobs:
  job-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Pull code"
      - run: echo "Run migrations"
      - run: echo "Generate binaries"
      - run: echo "Post version"